server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/login/**
          filters: AuthenticationFilter
        - id: auth-service-2
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
          filters: AuthenticationFilter
        - id: task-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/task/**
          filters: AuthenticationFilter
        - id: accounting
          uri: http://localhost:8092
          predicates:
            - Path=/api/account/**
          filters: AuthenticationFilter
        - id: analytics
          uri: http://localhost:8093
          predicates:
            - Path=/api/analytics/**
          filters: AuthenticationFilter

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security: DEBUG