server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/login/**