server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/login/**
  main:
    allow-bean-definition-overriding: true