server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/login/**
          filters: AuthenticationFilter
        - id: auth-service-2
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
          filters: AuthenticationFilter
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security: DEBUG