/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.schemaregistry.user.usercreated;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserCreatedPayload extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 543786531019168765L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserCreatedPayload\",\"namespace\":\"com.example.schemaregistry.user.usercreated\",\"fields\":[{\"name\":\"publicId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"username\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userRole\",\"type\":{\"type\":\"enum\",\"name\":\"UserRole\",\"symbols\":[\"ADMIN\",\"MANAGER\",\"ACCOUNTANT\",\"POPUG\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserCreatedPayload> ENCODER =
      new BinaryMessageEncoder<UserCreatedPayload>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserCreatedPayload> DECODER =
      new BinaryMessageDecoder<UserCreatedPayload>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserCreatedPayload> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserCreatedPayload> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserCreatedPayload> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserCreatedPayload>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserCreatedPayload to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserCreatedPayload from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserCreatedPayload instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserCreatedPayload fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String publicId;
  @Deprecated public java.lang.String username;
  @Deprecated public com.example.schemaregistry.user.usercreated.UserRole userRole;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserCreatedPayload() {}

  /**
   * All-args constructor.
   * @param publicId The new value for publicId
   * @param username The new value for username
   * @param userRole The new value for userRole
   */
  public UserCreatedPayload(java.lang.String publicId, java.lang.String username, com.example.schemaregistry.user.usercreated.UserRole userRole) {
    this.publicId = publicId;
    this.username = username;
    this.userRole = userRole;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return publicId;
    case 1: return username;
    case 2: return userRole;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: publicId = value$ != null ? value$.toString() : null; break;
    case 1: username = value$ != null ? value$.toString() : null; break;
    case 2: userRole = (com.example.schemaregistry.user.usercreated.UserRole)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'publicId' field.
   * @return The value of the 'publicId' field.
   */
  public java.lang.String getPublicId() {
    return publicId;
  }


  /**
   * Sets the value of the 'publicId' field.
   * @param value the value to set.
   */
  public void setPublicId(java.lang.String value) {
    this.publicId = value;
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.String getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.String value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'userRole' field.
   * @return The value of the 'userRole' field.
   */
  public com.example.schemaregistry.user.usercreated.UserRole getUserRole() {
    return userRole;
  }


  /**
   * Sets the value of the 'userRole' field.
   * @param value the value to set.
   */
  public void setUserRole(com.example.schemaregistry.user.usercreated.UserRole value) {
    this.userRole = value;
  }

  /**
   * Creates a new UserCreatedPayload RecordBuilder.
   * @return A new UserCreatedPayload RecordBuilder
   */
  public static com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder newBuilder() {
    return new com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder();
  }

  /**
   * Creates a new UserCreatedPayload RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserCreatedPayload RecordBuilder
   */
  public static com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder newBuilder(com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder other) {
    if (other == null) {
      return new com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder();
    } else {
      return new com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder(other);
    }
  }

  /**
   * Creates a new UserCreatedPayload RecordBuilder by copying an existing UserCreatedPayload instance.
   * @param other The existing instance to copy.
   * @return A new UserCreatedPayload RecordBuilder
   */
  public static com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder newBuilder(com.example.schemaregistry.user.usercreated.UserCreatedPayload other) {
    if (other == null) {
      return new com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder();
    } else {
      return new com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserCreatedPayload instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserCreatedPayload>
    implements org.apache.avro.data.RecordBuilder<UserCreatedPayload> {

    private java.lang.String publicId;
    private java.lang.String username;
    private com.example.schemaregistry.user.usercreated.UserRole userRole;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.publicId)) {
        this.publicId = data().deepCopy(fields()[0].schema(), other.publicId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userRole)) {
        this.userRole = data().deepCopy(fields()[2].schema(), other.userRole);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserCreatedPayload instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.schemaregistry.user.usercreated.UserCreatedPayload other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.publicId)) {
        this.publicId = data().deepCopy(fields()[0].schema(), other.publicId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userRole)) {
        this.userRole = data().deepCopy(fields()[2].schema(), other.userRole);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'publicId' field.
      * @return The value.
      */
    public java.lang.String getPublicId() {
      return publicId;
    }


    /**
      * Sets the value of the 'publicId' field.
      * @param value The value of 'publicId'.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder setPublicId(java.lang.String value) {
      validate(fields()[0], value);
      this.publicId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'publicId' field has been set.
      * @return True if the 'publicId' field has been set, false otherwise.
      */
    public boolean hasPublicId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'publicId' field.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder clearPublicId() {
      publicId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.String getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder setUsername(java.lang.String value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userRole' field.
      * @return The value.
      */
    public com.example.schemaregistry.user.usercreated.UserRole getUserRole() {
      return userRole;
    }


    /**
      * Sets the value of the 'userRole' field.
      * @param value The value of 'userRole'.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder setUserRole(com.example.schemaregistry.user.usercreated.UserRole value) {
      validate(fields()[2], value);
      this.userRole = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userRole' field has been set.
      * @return True if the 'userRole' field has been set, false otherwise.
      */
    public boolean hasUserRole() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userRole' field.
      * @return This builder.
      */
    public com.example.schemaregistry.user.usercreated.UserCreatedPayload.Builder clearUserRole() {
      userRole = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserCreatedPayload build() {
      try {
        UserCreatedPayload record = new UserCreatedPayload();
        record.publicId = fieldSetFlags()[0] ? this.publicId : (java.lang.String) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.String) defaultValue(fields()[1]);
        record.userRole = fieldSetFlags()[2] ? this.userRole : (com.example.schemaregistry.user.usercreated.UserRole) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserCreatedPayload>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserCreatedPayload>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserCreatedPayload>
    READER$ = (org.apache.avro.io.DatumReader<UserCreatedPayload>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.publicId);

    out.writeString(this.username);

    out.writeEnum(this.userRole.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.publicId = in.readString();

      this.username = in.readString();

      this.userRole = com.example.schemaregistry.user.usercreated.UserRole.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.publicId = in.readString();
          break;

        case 1:
          this.username = in.readString();
          break;

        case 2:
          this.userRole = com.example.schemaregistry.user.usercreated.UserRole.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










