/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.schemaregistry.user.usercreated;
@org.apache.avro.specific.AvroGenerated
public enum UserRole implements org.apache.avro.generic.GenericEnumSymbol<UserRole> {
  ADMIN, MANAGER, ACCOUNTANT, POPUG  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserRole\",\"namespace\":\"com.example.schemaregistry.user.usercreated\",\"symbols\":[\"ADMIN\",\"MANAGER\",\"ACCOUNTANT\",\"POPUG\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
